### PR TITLE
Add 404 HTML page

### PR DESCRIPTION
**Pull request by jamietanna**
As part of https://github.com/hoodiehq/hoodie/pull/607, we need to add a
404 page to return to the client.

### CODE REVIEW

**Comment by gr2m** [comment]
see my comment at https://github.com/jamietanna/hoodie/commit/b18d0ccf1d62f230be71fb72823944a00da8d46b#commitcomment-19475920

**Comment by gr2m** [comment]
what would make senses though is to check if the request is an HTML request. If it’s a request for an image or  a CSS or JS file, then we should server a 404 page 👍

**Comment by jamietanna** [comment]
@gr2m, little confused as to what you mean?

So you're saying that `if(isHoodiePath)`, we should do a `reply.continue()`, as it was in https://github.com/jamietanna/hoodie/commit/b18d0ccf1d62f230be71fb72823944a00da8d46b#diff-43557d6060003ff6997c94943ed23a82L118? Would this then close https://github.com/hoodiehq/hoodie/pull/607, as it is no longer needed then? Or would we still need that for returning to CSS/JS/image paths?

If so, I assume we'd have to match the requested URI, and check if it's a CSS/JS/image path? What file extensions would we want to match on for images? PNG, JPG?

**Comment by gr2m** [comment]
> So you're saying that if(isHoodiePath), we should do a reply.continue(), as it was in jamietanna/hoodie@b18d0cc#diff-43557d6060003ff6997c94943ed23a82L118? Would this then close hoodiehq/hoodie#607, as it is no longer needed then? Or would we still need that for returning to CSS/JS/image paths?

Yes I would still return it for asset paths with a file extension that isn’t `.htm` or `.html`

> If so, I assume we'd have to match the requested URI, and check if it's a CSS/JS/image path? What file extensions would we want to match on for images? PNG, JPG?

I would match any file extension but the ones mentioned above. Many html pages don’t have a file extension at all as they are folder names

**Comment by jamietanna** [comment]
As per changes in https://github.com/hoodiehq/hoodie/pull/607 is now _not_ needed.

**Pull request closed without merging**
