### PR TITLE
Enable semantic-release

### LINKED ISSUE #2: setup continuous deployment with semantic-release
run `semantic-release-cli setup` with `hoodiebot` GitHub & `hoodie` npm user.

### PR DESCRIPTION
**Pull request by finnp**
This should enable `semantic-release`  and publish `@hoodie/store` on npm. Closes #2

### CODE REVIEW

**Comment by gr2m** [comment]
LGTM ping @hoodiehq/maintainers

**Comment by gr2m** [comment]
note that I only enabled the `lgtm.co` integration now, so 2nd LGTM might not make it green, but admins can merge anyway

**Comment by boennemann** [comment]
LGTM

**Comment by gr2m** [comment]
releasd as [1.0.0](https://www.npmjs.com/package/@hoodie/store) :+1:

**Comment by espy** [comment]
Woooo :rocket:

**Pull request merged**
